### ISSUE TITLE
Discussion: Example mergekit

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/model-merge-kit#1]
1. Clone repo
```
git clone https://github.com/cg123/mergekit.git
```
2. Install dependencies
```
cd mergekit
pip install -e .
```
3. Create YAML
From 2 model_id + 1 base_model
- base_model: mistralai/Mistral-7B-v0.1
- model: janhq/supermario-v2
- model: janhq/supermario-slerp-v2
- 
```
slices:
  - sources:
      - model: janhq/supermario-slerp-v2
        layer_range: [0, 32]
      - model: janhq/supermario-v2
        layer_range: [0, 32]
merge_method: slerp
base_model: janhq/supermario-slerp-v2
parameters:
  t:
    - filter: self_attn
      value: [0, 0.5, 0.3, 0.7, 1] #This can be changed to perform better
    - filter: mlp
      value: [1, 0.5, 0.7, 0.3, 0]
    - value: 0.5
dtype: bfloat16
```
4. Run
```
mergekit-yaml path/to/your/config.yml ./output-model-directory --cuda
```
