### ISSUE TITLE
Discussion: CI for hyperparameters search

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/model-merge-kit#2]
**Motivation**
We have many way to tune the value for each layer when merging model

**Discussion**
This is the best YAML merging template we have for now

```
slices:
  - sources:
      - model: viethq188/LeoScorpius-7B-Chat-DPO
        layer_range: [0, 32] 
      - model: GreenNode/GreenNodeLM-7B-v1olet
        layer_range: [0, 32]
merge_method: slerp
base_model: GreenNode/GreenNodeLM-7B-v1olet
parameters:
  t:
    - filter: lm_head 
      value: [0.55]
    - filter: embed_tokens
      value: [0.7]
    - filter: self_attn
      value: [0.65, 0.35]
    - filter: mlp
      value:  [0.35, 0.65]
    - filter: layernorm
      value: [0.4, 0.6]
    - filter: modelnorm
      value: [0.6]
    - value: 0.5 # fallback for rest of tensors
dtype: bfloat16
```

**Reference**
After researching: the sweet spot of the `value` is around [0.4 - 0.7] but there are 2 ways of using the `value`
1. Static: Use only 1 number for each
- For this approach I think we can run [0.4-0.7] with 0.05 bins -> we will have a total of 49 models 
2. Gradient: Use it as a list 
- Let's discuss more later (Updating)

**GOAL**
To find the secret sauce

**Additional context**
We should have an evaluation for the model. I proposed a quick test:
-> Cut down the GSM8K, ARC, TruthfulQA into 10% and the criteria is model has >65 AVG we will keep. so we could screen models
